
//GET ALL USERS

export const GET_ALL_PRODUCT = "GET_ALL_PRODUCT";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const GET_PRODUCT_BY_ID = "GET_PRODUCT_BY_ID";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
